In [1]:
import sys
sys.path.append("/u/dssc/zenocosini/helm_suite/MCQA_Benchmark")
from metrics.query import DataFrameQuery
from common.utils import *
from metrics.utils import *

#from sklearn.feature_selection import mutual_info_regression MISSIN?
from dadapy.data import Data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
from collections import Counter
#!export OMP_NUM_THREADS=1

In [2]:
dict_query = {"method":"last",
              "model_name":  "meta-llama/Llama-3-8b-hf",
              "train_instances": 0}                               
tsm = TensorStorageManager()
query = DataFrameQuery(dict_query)
hidden_states,logits, hidden_states_stat = tsm.retrieve_tensor(query, "npy")

In [3]:
num_layers = hidden_states.shape[1]

In [4]:
subjects = hidden_states_stat["subjects"]

KeyError: 'subjects'

In [ ]:
mask = np.load("/orfeo/scratch/dssc/zenocosini/mmlu_result/test_mask_100.npy")
layer_data = hidden_states[:,20,:]
layer_data = layer_data[mask] 
base_unique, base_idx, base_inverse = np.unique(layer_data, axis=0, return_index=True, return_inverse=True)
indices = np.sort(base_idx)
base_repr = layer_data[indices]
subjects = subjects[indices]

#do clustering
d = data.Data(coordinates = base_repr)
ids, _, _ = d.return_id_scaling_gride(range_max=100)
d.set_id(ids[3])
d.compute_density_kNN(k=16)
assignment = d.compute_clustering_ADP(Z=1.6, halo=False)


In [22]:
base_unique[0]

array([-0.09,  0.66,  0.29, ..., -0.57, -0.03, -0.19], dtype=float32)

In [21]:
base_idx

array([1306, 4717, 3389, ..., 3319,  309,  383])

In [25]:
layer_data[1306]

array([-0.09,  0.66,  0.29, ..., -0.57, -0.03, -0.19], dtype=float32)